{{- if .Values.avp.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: argocd 
type: Opaque
stringData:
  AVP_TYPE: gcpsecretmanager
{{- end -}}
