{{- if and .Values.ingress.enabled .Values.iap.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "gke-argocd.name" . }}-backend-config
  namespace: {{ $.Release.Namespace }}
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: {{ include "gke-argocd.name" . }}-iap-secret
  connectionDraining:
    drainingTimeoutSec: 1800
  timeoutSec: 1800
{{- end -}}
