{{- if .Values.iap.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gke-argocd.name" . }}-iap-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: argocd 
type: Opaque
data:
  client_id: {{ .Values.iap.client_id | b64enc | quote }}
  client_secret: {{ .Values.iap.client_secret | b64enc | quote }}
{{- end -}}